    
spring:   
  datasource:    
    url: jdbc:mysql://localhost:3306/redis_demo01?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345
    
 
logging:
  level:   
    org.hibernate.type: trace
 
########## Custom App Props #############
google:
  books:
    api:
      url: https://www.googleapis.com/books/v1/volumes/{id}
 

 
    
  



