    
spring:   
  datasource:    
    url: jdbc:mysql://localhost:3306/redis_demo01?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345
    
  #cache:
    #redis:
      #time-to-live: 10
      
  data:
    redis:
      client-name: demo-cache
      host: 192.168.1.63
      #user that has access to read keys of this app (ACL SETUSER sasiperi on >12345 ~demo-cache:* &* +@all)
      username: sasiperi
      password: 12345
      #user that has NO access to read keys of this app (ACL SETUSER sasiperi01 on >123456 ~music:* &* +@all)
      #username: sasiperi01
      #password: 123456
      

logging:
  level:   
    org.hibernate.type: trace
 
########## Custom App Props #############
google:
  books:
    api:
      url: https://www.googleapis.com/books/v1/volumes/{id}
 

 
    
  



